grpc:
  services:
    -
      name: master
      port: 9999

map-reduce:
  workers:
    -
      ip: 192.168.1.102:8888
      region: 1
      room: 1
      username: yinan
      password: Q1w2e3r4t5
#    -
#      ip: 127.0.0.1:9090
#      region: 2 # 地区
#      room: 1 # 机房，为了做临近加载
#    -
#      ip: 127.0.0.1:9090
#      region: 3
#      room: 2

  sharding:
    infos:
      - ip: 192.168.1.102:22
        username: yinan
        password: Q1w2e3r4t5
        location: /home/yinan/1.txt # 默认数据已经分片
      - ip: 192.168.1.102:22
        username: yinan
        password: Q1w2e3r4t5
        location: /home/yinan/2.txt
